spring.application.name=p02

server.port=${PORT:8080}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-millis=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework.security=INFO